import { db, emailsTable, aiDecisionsTable, senderMemoryTable, syncStateTable } from "@workspace/db";
import { randomUUID } from "crypto";

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000);
const minsAgo = (m: number) => new Date(now.getTime() - m * 60 * 1000);

const emails = [
  {
    id: randomUUID(),
    gmailId: "msg_001",
    threadId: "thread_001",
    subject: "Your payment of $847.00 failed — Action required",
    from: "Stripe",
    fromEmail: "no-reply@stripe.com",
    to: "user@example.com",
    snippet: "Your payment of $847.00 on your Pro plan failed. Please update your payment method to avoid service interruption.",
    body: "Your payment of $847.00 on your Pro plan failed. Please update your payment method to avoid service interruption. Your account will be suspended in 24 hours if payment is not received.",
    isRead: false,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: minsAgo(15),
    category: "CRITICAL",
    priorityScore: 97,
    urgency: "critical",
    bundledCount: 1,
  },
  {
    id: randomUUID(),
    gmailId: "msg_002",
    threadId: "thread_002",
    subject: "Your security code is 847291",
    from: "GitHub",
    fromEmail: "noreply@github.com",
    to: "user@example.com",
    snippet: "Your GitHub authentication code is 847291. This code expires in 10 minutes.",
    body: "Your GitHub authentication code is 847291. This code expires in 10 minutes. If you didn't request this, please secure your account immediately.",
    isRead: false,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: minsAgo(3),
    category: "CRITICAL",
    priorityScore: 99,
    urgency: "critical",
    bundledCount: 1,
  },
  {
    id: randomUUID(),
    gmailId: "msg_003",
    threadId: "thread_003",
    subject: "Re: Q4 product roadmap discussion",
    from: "Sarah Chen",
    fromEmail: "sarah.chen@company.com",
    to: "user@example.com",
    snippet: "Hey, following up on our conversation yesterday. I think we need to revisit the timeline for the API integration. Can we sync tomorrow?",
    body: "Hey, following up on our conversation yesterday. I think we need to revisit the timeline for the API integration. The engineering team flagged some blockers we didn't account for. Can we sync tomorrow morning? I'm free 9-11am PST.",
    isRead: false,
    isStarred: true,
    labels: ["INBOX"],
    receivedAt: hoursAgo(1),
    category: "PRIMARY",
    priorityScore: 88,
    urgency: "high",
    bundledCount: 1,
  },
  {
    id: randomUUID(),
    gmailId: "msg_004",
    threadId: "thread_004",
    subject: "Interview invitation: Senior Engineer role at Anthropic",
    from: "Emma Rodriguez",
    fromEmail: "emma@anthropic.com",
    to: "user@example.com",
    snippet: "We reviewed your application and would love to schedule a technical interview. Please let us know your availability for next week.",
    body: "Hi,\n\nWe reviewed your application for the Senior Engineer role and were very impressed. We'd love to schedule a technical interview for next week.\n\nPlease let us know your availability and we'll confirm a time that works.\n\nBest,\nEmma Rodriguez\nRecruiting, Anthropic",
    isRead: false,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: hoursAgo(2),
    category: "PRIMARY",
    priorityScore: 92,
    urgency: "high",
    bundledCount: 1,
  },
  {
    id: randomUUID(),
    gmailId: "msg_005",
    threadId: "thread_005",
    subject: "Your AWS bill for March 2026 is ready",
    from: "Amazon Web Services",
    fromEmail: "billing@amazon.com",
    to: "user@example.com",
    snippet: "Your AWS bill for March 2026 is $1,243.87. View your detailed usage and billing statement.",
    body: "Your AWS bill for March 2026 is $1,243.87. View your detailed usage and billing statement in the AWS console.",
    isRead: true,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: hoursAgo(4),
    category: "TRANSACTIONS",
    priorityScore: 72,
    urgency: "medium",
    bundledCount: 1,
  },
  {
    id: randomUUID(),
    gmailId: "msg_006",
    threadId: "thread_006",
    subject: "Order confirmed: MacBook Pro M4 Max",
    from: "Apple Store",
    fromEmail: "no_reply@email.apple.com",
    to: "user@example.com",
    snippet: "Thank you for your order! Your MacBook Pro M4 Max will arrive in 3-5 business days.",
    body: "Thank you for your order #W123456789! Your MacBook Pro M4 Max ($3,499.00) will arrive in 3-5 business days. Tracking will be sent once your order ships.",
    isRead: true,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: hoursAgo(6),
    category: "TRANSACTIONS",
    priorityScore: 65,
    urgency: "medium",
    bundledCount: 1,
  },
  {
    id: randomUUID(),
    gmailId: "msg_007",
    threadId: "thread_007",
    subject: "Can you review my PR before EOD?",
    from: "Marcus Johnson",
    fromEmail: "marcus.j@company.com",
    to: "user@example.com",
    snippet: "Hey! I just pushed the auth refactor PR. It's blocking the release. Would you be able to take a look before EOD? Already pinged Alex.",
    body: "Hey! I just pushed the auth refactor PR (#847). It's blocking the v2.1 release. Would you be able to take a look before EOD? Already pinged Alex but she's out. The changes are mostly in src/auth/ — shouldn't take more than 20 mins.",
    isRead: false,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: hoursAgo(3),
    category: "PRIMARY",
    priorityScore: 85,
    urgency: "high",
    bundledCount: 1,
  },
  {
    id: randomUUID(),
    gmailId: "msg_008",
    threadId: "thread_008",
    subject: "Your LinkedIn connection request was accepted",
    from: "LinkedIn",
    fromEmail: "invitations@linkedin.com",
    to: "user@example.com",
    snippet: "David Kim has accepted your connection request. You are now connected.",
    body: "David Kim (VP Engineering at TechCorp) has accepted your connection request. You are now connected on LinkedIn.",
    isRead: true,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: hoursAgo(8),
    category: "SOCIAL",
    priorityScore: 25,
    urgency: "low",
    bundledCount: 3,
  },
  {
    id: randomUUID(),
    gmailId: "msg_009",
    threadId: "thread_009",
    subject: "🔥 50% off all courses — 24 hours only!",
    from: "Udemy",
    fromEmail: "info@udemy.com",
    to: "user@example.com",
    snippet: "Huge flash sale! 50% off all courses for the next 24 hours. Don't miss your chance to learn something new.",
    body: "Huge flash sale! 50% off ALL courses for the next 24 hours. Our most popular courses are going fast. Use code FLASH50 at checkout.",
    isRead: true,
    isStarred: false,
    labels: ["INBOX", "PROMOTIONS"],
    receivedAt: hoursAgo(5),
    category: "PROMOTIONS",
    priorityScore: 10,
    urgency: "low",
    bundledCount: 7,
  },
  {
    id: randomUUID(),
    gmailId: "msg_010",
    threadId: "thread_010",
    subject: "Notion AI feature update — What's new in March",
    from: "Notion",
    fromEmail: "team@mail.notion.so",
    to: "user@example.com",
    snippet: "We've shipped 12 new AI features this month including improved writing assistance, smarter search, and better integrations.",
    body: "We've shipped 12 new AI features this month including improved writing assistance, smarter search, and better integrations. Here's what's new...",
    isRead: false,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: hoursAgo(10),
    category: "PROMOTIONS",
    priorityScore: 18,
    urgency: "low",
    bundledCount: 1,
  },
  {
    id: randomUUID(),
    gmailId: "msg_011",
    threadId: "thread_011",
    subject: "Contract renewal — please sign by April 1st",
    from: "DocuSign",
    fromEmail: "dse@docusign.net",
    to: "user@example.com",
    snippet: "You have a document waiting for your signature. Your contractor agreement renewal requires your signature by April 1st.",
    body: "You have a document waiting for your signature. Your contractor agreement renewal (Consulting Agreement 2026) requires your signature by April 1st, 2026. Click below to review and sign.",
    isRead: false,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: hoursAgo(12),
    category: "PRIMARY",
    priorityScore: 90,
    urgency: "high",
    bundledCount: 1,
  },
  {
    id: randomUUID(),
    gmailId: "msg_012",
    threadId: "thread_012",
    subject: "Weekly digest: Top stories in AI",
    from: "The Batch",
    fromEmail: "thebatch@deeplearning.ai",
    to: "user@example.com",
    snippet: "This week: GPT-5 benchmarks, Gemini Ultra 3, and the latest from DeepMind. Plus: should you be worried about AI agents?",
    body: "This week in AI: GPT-5 benchmarks show impressive reasoning gains, Gemini Ultra 3 launches, and DeepMind releases new research. Plus our take on AI agents.",
    isRead: false,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: hoursAgo(20),
    category: "SOCIAL",
    priorityScore: 30,
    urgency: "low",
    bundledCount: 1,
  },
  {
    id: randomUUID(),
    gmailId: "msg_013",
    threadId: "thread_013",
    subject: "Your Vercel deployment failed",
    from: "Vercel",
    fromEmail: "noreply@vercel.com",
    to: "user@example.com",
    snippet: "Deployment failed for production branch. Build error in /app/api/route.ts. Click to view logs.",
    body: "Your deployment to production has failed.\n\nProject: my-saas-app\nBranch: main\nError: Build failed in /app/api/route.ts\n\nView the full error logs in your dashboard.",
    isRead: false,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: minsAgo(45),
    category: "CRITICAL",
    priorityScore: 95,
    urgency: "critical",
    bundledCount: 1,
  },
  {
    id: randomUUID(),
    gmailId: "msg_014",
    threadId: "thread_014",
    subject: "You're almost out of storage (92% full)",
    from: "Google Drive",
    fromEmail: "drive-shares-noreply@google.com",
    to: "user@example.com",
    snippet: "Your Google account storage is 92% full. Upgrade to Google One to get more storage and keep all your files.",
    body: "Your Google account storage is 92% full. You're using 14.7 GB of your 15 GB. When you run out of storage, you won't be able to save new files, photos, or emails.",
    isRead: true,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: hoursAgo(16),
    category: "PRIMARY",
    priorityScore: 68,
    urgency: "medium",
    bundledCount: 1,
  },
  {
    id: randomUUID(),
    gmailId: "msg_015",
    threadId: "thread_015",
    subject: "Re: Dinner plans Saturday?",
    from: "Alex Thompson",
    fromEmail: "alex.t@gmail.com",
    to: "user@example.com",
    snippet: "Sounds great! I'll make reservations at Nobu for 7pm. Should I add the others to this thread?",
    body: "Sounds great! I'll make reservations at Nobu for 7pm. Should I add Mike and Jenny to this thread? Let me know if you want to change the time.",
    isRead: false,
    isStarred: false,
    labels: ["INBOX"],
    receivedAt: hoursAgo(7),
    category: "PRIMARY",
    priorityScore: 62,
    urgency: "medium",
    bundledCount: 1,
  },
];

const decisions = [
  {
    id: randomUUID(),
    emailId: emails[0].id,
    category: "CRITICAL",
    priorityScore: 97,
    urgency: "critical",
    recommendedAction: "reply",
    confidence: 0.98,
    reason: "Payment failure requires immediate action to prevent service loss",
    summary: "Your Stripe subscription payment of $847.00 failed. Service will be suspended in 24 hours without payment.",
    keyPoints: ["Payment of $847.00 failed", "24-hour deadline before suspension", "Update payment method required"],
  },
  {
    id: randomUUID(),
    emailId: emails[1].id,
    category: "CRITICAL",
    priorityScore: 99,
    urgency: "critical",
    recommendedAction: "ignore",
    confidence: 0.99,
    reason: "OTP code — time-sensitive, expires in 10 minutes",
    summary: "GitHub authentication code 847291 that expires in 10 minutes. Use immediately if you requested it.",
    keyPoints: ["OTP expires in 10 minutes", "Only use if you requested login", "Flag if unexpected"],
  },
  {
    id: randomUUID(),
    emailId: emails[2].id,
    category: "PRIMARY",
    priorityScore: 88,
    urgency: "high",
    recommendedAction: "reply",
    confidence: 0.91,
    reason: "Known colleague requesting a sync — reply needed",
    summary: "Sarah Chen wants to revisit the Q4 roadmap timeline due to engineering blockers. She's free 9-11am PST tomorrow.",
    keyPoints: ["Engineering blockers found", "Wants sync tomorrow 9-11am PST", "Related to API integration timeline"],
  },
  {
    id: randomUUID(),
    emailId: emails[3].id,
    category: "PRIMARY",
    priorityScore: 92,
    urgency: "high",
    recommendedAction: "reply",
    confidence: 0.95,
    reason: "Job interview invitation — time-sensitive response needed",
    summary: "Anthropic wants to schedule a Senior Engineer technical interview. They reviewed your application positively.",
    keyPoints: ["Interview invitation from Anthropic", "Need to share availability for next week", "Senior Engineer role"],
  },
  {
    id: randomUUID(),
    emailId: emails[4].id,
    category: "TRANSACTIONS",
    priorityScore: 72,
    urgency: "medium",
    recommendedAction: "track",
    confidence: 0.88,
    reason: "Monthly bill — review for unexpected charges",
    summary: "AWS March 2026 bill is $1,243.87. Review for unexpected usage spikes.",
    keyPoints: ["$1,243.87 charge", "Review for anomalies", "Archive after review"],
  },
  {
    id: randomUUID(),
    emailId: emails[5].id,
    category: "TRANSACTIONS",
    priorityScore: 65,
    urgency: "medium",
    recommendedAction: "track",
    confidence: 0.92,
    reason: "Order confirmation — track delivery",
    summary: "MacBook Pro M4 Max order confirmed for $3,499. Arrives in 3-5 business days.",
    keyPoints: ["Order #W123456789", "$3,499.00 charge", "Arrives in 3-5 business days"],
  },
  {
    id: randomUUID(),
    emailId: emails[6].id,
    category: "PRIMARY",
    priorityScore: 85,
    urgency: "high",
    recommendedAction: "reply",
    confidence: 0.93,
    reason: "Colleague needs code review before EOD to unblock release",
    summary: "Marcus needs PR #847 reviewed before EOD to unblock the v2.1 release. Changes are in src/auth/ (~20 min review).",
    keyPoints: ["PR #847 blocking v2.1 release", "EOD deadline", "Changes in src/auth/ — 20min review"],
  },
  {
    id: randomUUID(),
    emailId: emails[10].id,
    category: "PRIMARY",
    priorityScore: 90,
    urgency: "high",
    recommendedAction: "reply",
    confidence: 0.96,
    reason: "Legal document requiring signature — April 1st deadline",
    summary: "Contract renewal awaiting your signature in DocuSign. Must be signed by April 1st, 2026.",
    keyPoints: ["Consulting Agreement renewal", "Deadline: April 1st 2026", "DocuSign — requires action now"],
  },
  {
    id: randomUUID(),
    emailId: emails[12].id,
    category: "CRITICAL",
    priorityScore: 95,
    urgency: "critical",
    recommendedAction: "reply",
    confidence: 0.97,
    reason: "Production deployment failure needs immediate investigation",
    summary: "Vercel production deployment failed with build error in /app/api/route.ts. Investigate and fix immediately.",
    keyPoints: ["Production build failed", "Error in /app/api/route.ts", "Check Vercel logs for details"],
  },
];

async function seed() {
  console.log("Seeding database...");

  await db.delete(aiDecisionsTable);
  await db.delete(emailsTable);
  await db.delete(senderMemoryTable);
  await db.delete(syncStateTable);

  console.log("Inserting emails...");
  for (const email of emails) {
    await db.insert(emailsTable).values(email).onConflictDoNothing();
  }

  console.log("Inserting AI decisions...");
  for (const decision of decisions) {
    await db.insert(aiDecisionsTable).values({
      ...decision,
      keyPoints: decision.keyPoints,
      createdAt: new Date(),
      updatedAt: new Date(),
    }).onConflictDoNothing();
  }

  const senderStats: Record<string, { name: string; count: number; replyCount: number }> = {};
  for (const email of emails) {
    if (!senderStats[email.fromEmail]) {
      senderStats[email.fromEmail] = { name: email.from, count: 0, replyCount: 0 };
    }
    senderStats[email.fromEmail].count++;
  }

  const knownImportant = ["sarah.chen@company.com", "marcus.j@company.com", "alex.t@gmail.com"];
  for (const [fromEmail, stats] of Object.entries(senderStats)) {
    const isImportant = knownImportant.includes(fromEmail);
    await db.insert(senderMemoryTable).values({
      id: randomUUID(),
      fromEmail,
      displayName: stats.name,
      totalEmails: stats.count,
      openCount: Math.floor(stats.count * 0.7),
      replyCount: isImportant ? Math.floor(stats.count * 0.5) : 0,
      ignoreCount: isImportant ? 0 : Math.floor(stats.count * 0.3),
      archiveCount: 0,
      avgTimeSpentMs: isImportant ? 45000 : 5000,
      lastInteractionAt: new Date(),
      importanceScore: isImportant ? 0.8 : 0.3,
      createdAt: new Date(),
      updatedAt: new Date(),
    }).onConflictDoNothing();
  }

  await db.insert(syncStateTable).values({
    id: "main",
    status: "idle",
    lastSyncAt: new Date(),
    emailsSynced: emails.length,
    message: "Demo data loaded. Connect Gmail to sync real emails.",
    createdAt: new Date(),
    updatedAt: new Date(),
  }).onConflictDoNothing();

  console.log(`Seeded ${emails.length} emails, ${decisions.length} decisions`);
  console.log("Done!");
}

seed().catch(console.error).finally(() => process.exit(0));
